version: "3.7"

services:
  database_desafio:
    image: postgres
    container_name: database_desafio
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


